import sys
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(BASE_DIR)
import streamlit as st
import pandas as pd
from pathlib import Path

from chat import (
    build_graph,
    predict_logistic,
    predict_bert,
    predict_lstm,
    CSV_PATH,
)

# Streamlit App
st.set_page_config(page_title="Sentiment Analysis", layout="centered")

st.title("💬 Sentiment Analysis")
st.write(
    "Enter a review and choose a model to get sentiment prediction, confidence, "
    "and explanation generated by GPT4All."
)

#  Sidebar
with st.sidebar:
    st.header("Options")
    model_choice = st.selectbox("Choose Model", ["logistic", "bert", "lstm"])
    # include_dataset = st.checkbox("Include Dataset Insight", value=False)

#  Load Dataset
df = pd.read_csv(CSV_PATH)

#  User Input
user_input = st.text_area("Enter your text here:", height=120)

if st.button("Analyze Sentiment") and user_input.strip():
    # ---------------- Build Workflow ----------------
    workflow = build_graph(df)

    # ---------------- Prepare State ----------------
    state = {
        "user_input": user_input,
        "model_choice": model_choice,
        "prediction": None,
        "explanation": None,
        "dataset_insight": None,
    }

    # ---------------- Invoke Graph ----------------
    with st.spinner("Analyzing..."):
        final_state = workflow.invoke(state)

    # ---------------- Display Results ----------------
    pred = final_state["prediction"]
    st.subheader("🔹 Prediction")
    st.write(f"**Sentiment:** {pred['sentiment'].capitalize()}")
    st.write(f"**Confidence:** {pred['confidence']:.4f}")
    st.write(f"**Model Used:** {pred['model']}")

    st.subheader("✨ Explanation")
    st.write(final_state["explanation"])

    # if include_dataset and df is not None:
    #     st.subheader("📊 Dataset Insight")
    #     st.write(final_state["dataset_insight"])

st.info("Tip: Enter a review and select a model to see the prediction and explanation.")
